### ISSUE TITLE
add dependency to vue-auto-routing

### ISSUE THREAD

**Issue by AnWeber** [ktsn/vue-cli-plugin-auto-routing#15]
you are missing a dependency or peer dependency to vue-auto-routing.

**Comment by ktsn** [comment]
It will be injected into your project's dependencies when you invoke the plugin.
https://github.com/ktsn/vue-cli-plugin-auto-routing/blob/master/generator/index.js#L7

**Comment by AnWeber** [comment]
I added the dependency without the generator. In this use case I would prefer a peer depencendy to vue-auto-routing and vue-auto-layout to get a hint to the missing dependency.

Thanks for your fast response time.

**Comment by ktsn** [comment]
That's good idea. I just added vue-auto-routing in peerDeps.
I didn't add vue-router-layout because the user can use this plugin without it.

**Comment by AnWeber** [comment]
Thanks. Great work by the way. Keep going.
