### ISSUE TITLE
How to handle 404s?

### ISSUE THREAD

**Issue by wvffle** [ktsn/vue-cli-plugin-auto-routing#18]
Well, I have a problem with 404s.

If I create a file `pages/_.vue` or `pages/*.vue` it hangs the development server and I cannot test my app.

If I create a file `pages/_404.vue` it seems to work well but only for urls like `/something` but not for `/some/thing`

I don't want to create many files like `pages/_404/_404.vue` or any other like that. I'd like to handle 404s in one file.

Is there any way to do that?

**Comment by ktsn** [comment]
Just adding fallback route in your router option should be ok.  https://router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route

**Comment by wvffle** [comment]
That's the way I solved it:
```js
export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      component: RouterLayout,
      children: routes
    },
    {
      path: '*',
      component: RouterLayout,

      children: [{
        name: 'page-404',
        path: '',
        component: () => import('@/views/404.vue')
      }]
    }
  ]
})
```
