### ISSUE TITLE
Does it work with HttpVueLoader?

### ISSUE THREAD

**Issue by edmundophie** [ktsn/vue-cli-plugin-auto-routing#2]
Is it possible to use this plugin with [HttpVueLoader ](https://github.com/FranckFreiburger/http-vue-loader)?

I want to make a vue project that has auto routing feature and doesn't require me to compile/build using webpack everytime I add a new `.vue`page.

I'm imagining that it would be cool if I could just put in a new `.vue` page into the server directory and it instantly works when I access the filename url.

**Comment by ktsn** [comment]
I'm not sure about HttpVueLoader but thinking a similar idea recently. I'll take a look HttpVueLoader and post a comment in this thread if something moves forward.
Thanks for the info!

**Comment by ktsn** [comment]
Closing because this package wouldn't work with HttpVueLoader as it assumes the existence of webpack.
