### ISSUE TITLE
Failed to resolve loader: vue-cli-plugin-auto-routing/route-loader

### ISSUE THREAD

**Issue by sheandemontigny** [ktsn/vue-cli-plugin-auto-routing#32]
Hi!

When using the version 0.4.0 with `<route> ` custom block, i get the following error : 
`Failed to resolve loader: vue-cli-plugin-auto-routing/route-loader`

I believe the file `route-loader.js` is missing in the bundle.

**Comment by ktsn** [comment]
Thanks! It's included in v0.4.1
