### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Tsaukpaetra** [ktsn/vue-cli-plugin-auto-routing#42]
I installed according to the Overview section, but I'm not sure how to actually get it to activate. I do see the sample pages, but it doesn't appear to do anything?
The default App.vue page is still there being served, and it's not clear how to replace it with whatever is generated (or if it's generated?).

**Comment by ktsn** [comment]
Running `Overview` section in a brand new Vue CLI project works for me.
If you are using it in an existing project, you may not have `<router-view>` in your App.vue or not property set up router.js.

Also see [vue-auto-routing](https://github.com/ktsn/vue-auto-routing) and [vue-router-layout](https://github.com/ktsn/vue-router-layout)

**Comment by Tsaukpaetra** [comment]
This isn't an existing project, I literally did `vue create frontend` and followed the two remaining commands in the Overview section. 
What remained was a HelloWorld component that was duplicated in /pages/index.vue and App.vue calling it. 

What should `main.js` have in it to include the auto loader? I tried replacing the App.vue with the following:

```
<template>
 <router-view> 
</template>
```

Now it's just a blank page.

**Comment by Tsaukpaetra** [comment]
Found it.  Apparently you need the following main.js

```
import Vue from 'vue'
import App from './App.vue'
import router from './router'

Vue.config.productionTip = false

new Vue({
  router,
  render: h => h(App)
}).$mount('#app')
```

For whatever reason the installation didn't do that? 😖

Thanks for the help.

**Comment by ktsn** [comment]
If you install Vue router cli plugin, that does it for you.

**Comment by Tsaukpaetra** [comment]
Yeah, not sure why it didn't in my case but I have it resolved now so it's fine...
