### ISSUE TITLE
It is possible to use named views?

### ISSUE THREAD

**Issue by mouettxy** [ktsn/vue-cli-plugin-auto-routing#43]

**Comment by ktsn** [comment]
No, currently. If you need it, please describe the use case and why you can't achieve it with the current features. Thank you.

**Comment by mouettxy** [comment]
@ktsn Use case is render modal on child url (example: /users/ with modal in /users/:id) without rerender or any interact with parent component.

I found workaround that solves this for me, I just extend generated routes by vue-auto-routing with route object.
This is my current working code.

```js
import Router from 'vue-router'
import routes from 'vue-auto-routing'

routes.push({ name: 'userModal', path: 'user/:id?', components: { default: PageUser, modal: UserModal } })

export const router = new Router({
  routes: [
    {
      path: '/',
      component: RouterLayout,
      children: routes
    }
  ],
  mode: 'history'
})
```
But this looks a bit weird.
I need to use urls for modals, but no need to rerender parent component.

I hope I make myself clear.

**Comment by ktsn** [comment]
I guess you can just add `pages/users/index.vue` (with `<router-view>` in it) and `pages/users/index/_id.vue` for that use case.

**Comment by ktsn** [comment]
Closing since it seems that the above way solves the use case.

**Comment by shinyruo177** [comment]
I guess the case is:
https://v3.router.vuejs.org/guide/essentials/named-views.html#nested-named-views
Also similar to this issue in nuxt community:
https://github.com/nuxt-community/router-extras-module/issues/84
