### ISSUE TITLE
Can I pass component props to layout component?

### ISSUE THREAD

**Issue by yaquawa** [ktsn/vue-cli-plugin-auto-routing#61]
I'm wondering if it's possible to pass component props to layout component?

For example:

`pages/about.vue`
```vue
<template>
...
</template>

<script>
export default {
  layout: {
    name: 'foo',
    props: {title: 'bar'}
  }
}
</script>
```

`layouts/foo.vue`
```vue
<template>
  <div>
    <h1>{{ title }}</h1>
    <router-view />
  </div>
</template>

<script>
export default {
  props: {
    title: String
  }
}
</script>
```

**Comment by ktsn** [comment]
What is the use case of this?

**Comment by yaquawa** [comment]
Hi @ktsn, thanks for replying.
This is quite common in other template languages which have the concept of "layout".
I've shown the example as above(I've edited the syntax to match the PR I made).
If we can't pass properties to the target layout, we have to create as many layouts as the variation of "title".
Let me know if I have missed anything else. 
Thanks.

**Comment by ktsn** [comment]
https://github.com/ktsn/vue-router-layout/pull/275
