### ISSUE TITLE
[Feature Request] Default to not use optional parameters

### ISSUE THREAD

**Issue by yaquawa** [ktsn/vue-cli-plugin-auto-routing#64]
According to the readme:

> If you want to make route param required, create a directory for the param and add `index.vue` in the directory. In the above example, if you replace `users/_id.vue` with `users/_id/index.vue`, :id param will be required.

The current implementation automatically append the optional parameters `?` to the dynamic routes.
This feels like not so intuitively. I believe people will just expect a normal dynamic route without `?` appended.

My suggestion is make the default behavior to not appending the `?`, if one wish it be an optional parameter, they could append `?` to the filename on demand. 

Further more, the route could just be `:` + `filename.substring(1)`, this way we can define [Repeatable params](https://next.router.vuejs.org/guide/essentials/route-matching-syntax.html#repeatable-params) and [Custom Regexp in params](https://next.router.vuejs.org/guide/essentials/route-matching-syntax.html#custom-regexp-in-params) as well.

@ktsn 
If you are OK for this, I'd like send a PR, what do you think?

**Comment by ktsn** [comment]
`:` and `?` can be a reserved character.
https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words

**Comment by yaquawa** [comment]
@ktsn 
Can we have an option for the default behavior?
I don't know much about Nuxt, does it also have "optional parameters" as the default behavior? 
I think this is not the common pattern anyway.
