### ISSUE TITLE
Layout is not applied, if provided via Mixin

### ISSUE THREAD

**Issue by lqdchrm** [ktsn/vue-cli-plugin-auto-routing#9]
I would like to calculate the used layout dynamically for some pages. Therefore I try to provide the layout via mixin, but the default layout is always applied:

./pages/index.vue:
```
<template>
  <div class="home">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
// @ is an alias to /src
import HelloWorld from '@/components/debug/HelloWorld.vue'
import LayoutMix from '@/mixins/layout'

export default {
  name: 'home',
  mixins: [ LayoutMix ],
  components: { HelloWorld }
}
</script>
````

./mixins/layout.js
```
const layoutMixin = {
    layout: 'app'
}

export default layoutMixin;
```

Probably, at the time the layoutName is fetched, Mixins are not yet applied to the Component (please see:
https://github.com/ktsn/vue-router-layout/blob/1d1ba839755b95af3dd63c3939fa3560ea60a7dd/src/index.ts#L27) ?

**Comment by ktsn** [comment]
I've implement it in vue-router-layout v0.1.4. Please update it in your project.
